formularioJS/formularioJS/urls.py
# -*- coding: utf-8 -*-
"""formularioJS URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('selectsenlazados.urls')),
]

formularioJS/selectsenlazados/urls.py
# -*- coding: utf-8 -*-
"""!
Array que direcciona las urls del navegador a las vistas

@file selectsenlazados/urls.py
@author Angelo Osorio
@license Fundación CENDITEL (2018)
@version 1.0 - 2018
"""
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='agregarPoa'),
]

formularioJS/selectsenlazados/models.py
# -*- coding: utf-8 -*-
"""!
Modelos de datos para un ejemplo de selects anidados en un formulario

@file selectsenlazados/models.py
@author Angelo Osorio
"""

from __future__ import unicode_literals

from django.db import models



class Estado(models.Model):
    """
    Modelo que contiene los nombres de los estados

    @param nombre_estado            Nombre del Estado, type: varchar(250)
    @author                         Angelo Osorio (danielking.321 at gmail.com)
    """
    nombre_estado = models.CharField(max_length=250)
    def __unicode__(self):
        return self.nombre_estado



class Municipio(models.Model):
    """
    Modelo que contiene los nombres de los municipios

    @param nombre_municipio         Nombre del Municipio, type: varchar(250)
    @param estado_perteneciente     Estado al que pertenece, type: Clave foránea de Estado
    @author                         Angelo Osorio (danielking.321 at gmail.com)
    """
    nombre_municipio = models.CharField(max_length=250)
    estado_perteneciente = models.ForeignKey(Estado, on_delete=models.CASCADE)
    def __unicode__(self):
        return self.nombre_municipio



class Parroquia(models.Model):
    """
    Modelo que contiene los nombres de las parroquias

    @param nombre_parroquia         Nombre de la Parroquia, type: varchar(250)
    @param municipio_perteneciente  Municipio al que pertenece, type: Clave foránea de Municipio
    @author                         Angelo Osorio (danielking.321 at gmail.com)
    """
    nombre_parroquia = models.CharField(max_length=250)
    municipio_perteneciente = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    def __unicode__(self):
        return self.nombre_parroquia



class Poa(models.Model):
    """!
    Modelo que contiene los datos del poa
    
    @param nombre                   Nombre del poa, type: varchar(250)
    @param descripcion              Texto del poa, type: text
    @param estado                   Estado del poa, type: Clave foránea de Estado
    @param municipio                Municipio del poa, type: Clave foránea de Municipio
    @param parroquia                Parroquia del poa, type: Clave foránea de Parroquia
    @author                         Angelo Osorio (danielking.321 at gmail.com)
    """
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField()
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    parroquia = models.ForeignKey(Parroquia, on_delete=models.CASCADE)
    def __unicode__(self):
        return "%s de %s" % (self.nombre, self.estado)

formularioJS/selectsenlazados/forms.py
# -*- coding: utf-8 -*-
"""!
Clase para administrar los atributos de los inputs en el formulario respectivo

@file selectsenlazados/forms.py
@author Angelo Osorio
@license Fundación CENDITEL (2018)
@version 1.0 - 2018
"""

from django import forms
from .models import Poa


class AgregarPoaForm(forms.ModelForm):
    """
    Modelo de formulario para el formulario de agregar POA

    @author                         Angelo Osorio (danielking.321 at gmail.com)
    """
    class Meta:
        model = Poa
        fields = ('nombre', 'descripcion', 'estado', 'municipio', 'parroquia')

formularioJS/selectsenlazados/views.py
# -*- coding: utf-8 -*-
"""!
Vistas del módulo

@file selectsenlazados/views.py
@author Angelo Osorio
@license Fundación CENDITEL (2018)
@version 1.0 - 2018
"""


from __future__ import unicode_literals

from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect
from django.urls import reverse

from .models import Poa, Estado, Municipio, Parroquia
from .forms import AgregarPoaForm


## index
# (Consulta y muestra todos los poa, predeterminado como index del módulo)
#
# @param request:           la solicitud de la url de entrar a este método
# @return request:          la solicitud de la url de entrar a este método
# @return index.html:       el template que llenará
# @return context:          Guarda los datos que se mostrarán dentro del context, en una variable
#                           denominada Poas
#
# @author Angelo Osorio
##
def index(request):
    context = {
        'poas': Poa.objects.all().order_by('-id')
    }
    return render(request, 'selectsenlazados/index.html', context)



## add
# (Vista que administrará el formulario de agregar poas)
# 
# @param consulta_estados:      Contiene una consulta con los estados disponibles en la base de datos
# @param consulta_municipios:   Contiene una consulta con los municipios disponibles en la DB
# @param consulta_parroquias:   Contiene una consulta con las parroquias disponibles en la DB
# @param request:               la solicitud de la url de entrar a este método
# @return request:              la solicitud de la url de entrar a este método
# @return index.html:           el template que llenará
# @return context:              Guarda los datos que se mostrarán dentro del context, en una variable
#                               denominada Poas
#
# @author Angelo Osorio
##
def add(request):

    consulta_estados = Estado.objects.all()
    consulta_municipios = Municipio.objects.all()
    consulta_parroquias = Parroquia.objects.all()

    if request.method == "POST":
        form = AgregarPoaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = AgregarPoaForm()

    context = {
        'form' : form,
        'estados' : consulta_estados,
        'municipios' : consulta_municipios,
        'parroquias' : consulta_parroquias
    }

    return render(request, 'selectsenlazados/add.html', context)

formularioJS/selectsenlazados/templates/selectsenlazados/add.html
{% extends "selectsenlazados/base.html" %}
 
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}



    <!-- Nombre del POA -->
    <label for="id_nombre"> {{ form.nombre.label }} </label>
    <p> {{ form.nombre }} </p>



    <!-- Descripción del POA -->
    <label for="id_descripcion"> {{ form.descripcion.label }} </label>
    <p> {{ form.descripcion }} </p>



    <!-- Estado del POA -->
    <label for="id_estado"> {{ form.estado.label }} </label>
    <p>
      <select name="estado" required id="id_estado">
        <option value="">Seleccione un Estado</option>
        {% for estado in estados %}
          <option value="{{ estado.id }}">{{ estado.nombre_estado }}</option>
        {% endfor %}
      </select>
    </p>



    <!-- Municipio del POA -->
    <label for="id_municipio">{{ form.municipio.label }}</label>
    <p>
      <select name="municipio" id="id_municipio" required>
        <option value="">Seleccione un municipio</option>
      </select>
    </p>

    <!-- Parroquia del POA -->
    <label for="id_parroquia">{{ form.parroquia.label }}</label>
    <p>
      <select name="parroquia" id="id_parroquia" required>
        <option value="">Seleccione una parroquia</option>
      </select>
    </p>



    <br>
    <input type="submit" value="Send">
  </form>
  <script>
    (function(){

      /*
       * 1. Buscar el elemento en el DOM que hará que el segundo select sea llenado
       */
      var id_estado = document.getElementById("id_estado");
      var id_municipio = document.getElementById("id_municipio");
      var id_parroquia = document.getElementById("id_parroquia");


      /*
       * 2. Crear un array con los municipios de cada estado
       *
       * @for estado in estados           Se consultan los estados disponibles traídos desde la
       *                                  consulta en la base de datos.
       *
       * @param estado_{{ estado.id }}    Se crea un array por cada estado disponible en la base de
       *                                  datos.
       *
       * @for municipio in municipios     Se consultan los municipios disponibles traídos desde la
       *                                  consulta en la base de datos.
       *
       * @if municipio.estado_perteneciente.id == estado.id   Si el id del municipio concuerda con
       *                                                      el id del estado, mete el nombre del
       *                                                      municipio en el array del estado
       *                                                      correspondiente. 
       */

      {% for estado in estados %}

        var estado_{{ estado.id }} = new Array();
        var estado_{{ estado.id }}_id = new Array();

        {% for municipio in municipios %}
          {% if municipio.estado_perteneciente.id == estado.id %}

            var municipio_{{municipio.id }} = new Array();
            var municipio_{{municipio.id }}_id = new Array();
            estado_{{ estado.id }}.push('{{ municipio.nombre_municipio }}');
            estado_{{ estado.id }}_id.push('{{ municipio.id }}');

            {% for parroquia in parroquias %}

              {% if parroquia.municipio_perteneciente.id == municipio.id %}

                municipio_{{municipio.id }}.push('{{ parroquia.nombre_parroquia }}');
                municipio_{{municipio.id }}_id.push('{{ parroquia.id }}');

              {% endif %}

            {% endfor %}


          {% endif %}
        {% endfor %}

      {% endfor %}


      /*
       * 3. Crear el evento que escuchará e imprimirá las opciones al cambiar el select "estado" 
       */
      id_estado.addEventListener('change',function(){

        // Valor del select "id_estado"
        let estado_seleccionado = this.value;

        // Verifica la validez de estado_seleccionado
        if(estado_seleccionado != 0) {
 
          // Selecciona el array que se llame como el servicio que se seleccionó
          array_del_estado = eval("estado_" + estado_seleccionado);
          array_del_estado_id = eval("estado_" + estado_seleccionado + "_id");
 
          // Calcula el número de elementos que se imprimirá en el combobox
          cantidad_municipios = array_del_estado.length;
 
          // Se le asigna el largo de array al combobox
          id_municipio.length = cantidad_municipios + 1;

          id_municipio.options[0].value = "";
          id_municipio.options[0].text = "Seleccionar";
 
          // Imprime las opciones en el combobox
          for(i=0; i < cantidad_municipios; i++){
            id_municipio.options[i+1].value = array_del_estado_id[i];
            id_municipio.options[i+1].text = array_del_estado[i];
          }
 
        } else {

          // si no habia ninguna opt seleccionada, se eliminan  del select
          id_municipio.length = 1;

          //ponemos un guion en la unica opt que he dejado
          id_municipio.options[0].value="";
          id_municipio.options[0].text="Seleccione un municipio";
        }


      }, true);

      id_municipio.addEventListener('change',function(){

        // Valor del select "id_estado"
        let estado_seleccionado = this.value;

        // Verifica la validez de estado_seleccionado
        if(estado_seleccionado != 0) {
 
          // Selecciona el array que se llame como el servicio que se seleccionó
          array_del_estado = eval("municipio_" + estado_seleccionado);
          array_del_estado_id = eval("municipio_" + estado_seleccionado + "_id");
 
          // Calcula el número de elementos que se imprimirá en el combobox
          cantidad_municipios = array_del_estado.length;
 
          // Se le asigna el largo de array al combobox
          id_parroquia.length = cantidad_municipios + 1;

          id_parroquia.options[0].value = "";
          id_parroquia.options[0].text = "Seleccionar";
 
          // Imprime las opciones en el combobox
          for(i=0; i < cantidad_municipios; i++){
            id_parroquia.options[i+1].value = array_del_estado_id[i];
            id_parroquia.options[i+1].text = array_del_estado[i];
          }
 
        } else {

          // si no habia ninguna opt seleccionada, se eliminan  del select
          id_parroquia.length = 1;

          //ponemos un guion en la unica opt que he dejado
          id_parroquia.options[0].value="";
          id_parroquia.options[0].text="Seleccione un municipio";
        }


      }, true);
      })();
  </script>

{% endblock %}

formularioJS/selectsenlazados/templates/selectsenlazados/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Formulario JS</title>
  <style>
    table td {
      border-top: 3px dashed #000;
      padding: 10px 20px
    }
  </style>
</head>
<body>
  <h2>Formulario JS</h2>

  {% block content %}
  <!-- Contenido -->
  {% endblock %}

</body>
</html>

formularioJS/selectsenlazados/templates/selectsenlazados/index.html
{% extends "selectsenlazados/base.html" %}


{% block content %}

  <a href="add/">+ Agregar un poa</a>


  {% if poas %}
  <table>
    <thead>
      <th>POA</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Parroquia</th>
    </thead>
    <tbody>
    {% for poa in poas %}
          <tr>
            <td> {{ poa.nombre }} </td>
            <td> {{ poa.descripcion }} </td>
            <td> {{ poa.estado }} </td>
            <td> {{ poa.municipio }} </td>
            <td> {{ poa.parroquia }} </td>
          </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>No hay poas</p>
  {% endif %}

{% endblock %}